global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: 'BTS_model'
    honor_labels: true
    static_configs:
      - targets: ["IP_ML_SERVICE:8000", "IP_ML_SERVICE:8080"]
  - job_name: 'Resource_monitoring'
    scrape_interval: 15s
    static_configs:
      - targets: ["IP_RESOURCE_MANAGEMENT_SERVICE:8888"]

