global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: 'BTS_model'
    honor_labels: true
    static_configs:
      - targets: ["192.168.1.100:8000", "192.168.1.100:8080"]


